// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtMBpS9qN7aIbZbsFfEdsgyAUvDdfn2c0',
    appId: '1:332631748512:web:67dab64eabedd6636e3ec5',
    messagingSenderId: '332631748512',
    projectId: 'myntra-48d15',
    authDomain: 'myntra-48d15.firebaseapp.com',
    storageBucket: 'myntra-48d15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEeVCrKbETTlGLaSPmaIE-ta9NDhv5s90',
    appId: '1:332631748512:android:2a2e1014219ac5cc6e3ec5',
    messagingSenderId: '332631748512',
    projectId: 'myntra-48d15',
    storageBucket: 'myntra-48d15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3j6hcBL2xo7Ziyd7WWmrcEL1H5-tK79o',
    appId: '1:332631748512:ios:ad52fc5f85b2bd776e3ec5',
    messagingSenderId: '332631748512',
    projectId: 'myntra-48d15',
    storageBucket: 'myntra-48d15.firebasestorage.app',
    iosBundleId: 'com.example.myntraClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3j6hcBL2xo7Ziyd7WWmrcEL1H5-tK79o',
    appId: '1:332631748512:ios:ad52fc5f85b2bd776e3ec5',
    messagingSenderId: '332631748512',
    projectId: 'myntra-48d15',
    storageBucket: 'myntra-48d15.firebasestorage.app',
    iosBundleId: 'com.example.myntraClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtMBpS9qN7aIbZbsFfEdsgyAUvDdfn2c0',
    appId: '1:332631748512:web:01d56289d6afa0eb6e3ec5',
    messagingSenderId: '332631748512',
    projectId: 'myntra-48d15',
    authDomain: 'myntra-48d15.firebaseapp.com',
    storageBucket: 'myntra-48d15.firebasestorage.app',
  );
}
